service: website-monitor

# app and org for use with dashboard.serverless.com
app: website-monitor
org: quocvu

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  monitorAllSites:
    handler: monitor.allSites
    events:
      - schedule: rate(15 minutes)

# CloudFormation resources
resources:
  Resources:
    WebsiteMonitorErrorCountBucket:
      Type: AWS::S3::Bucket
      Properties:
        Tags:
          -
            Key: app,
            Value: website-monitor
          -
            Key: usage
            Value: store-error-counts
    WebsiteMonitorAlertsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: website-monitor
        Subscription:
          -
            Endpoint: ${param:PhoneNumber}
            Protocol: sms
    WebsiteMonitorLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 90
    WebsiteMonitorLogStream:
      Type: AWS::Logs::LogStream
      Properties:
        LogGroupName: WebsiteMonitorLogGroup

    WebsiteMonitorRole:
      Type: AWS::IAM::Role,
      Properties:
        Path: '/'
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          -
            PolicyName: website-monitor
            PolicyDocument:
              Version : 2012-10-17
              Statement:
                -
                  Action:
                    - s3:ListBucket
                  Effect: Allow
                  Resource:
                    - 'Fn::Join':
                      - ''
                      -
                        - 'arn:aws:s3:::'
                        - Ref: WebsiteMonitorErrorCountBucket
                -
                  Action:
                    - s3:GetObject
                    - s3:PutObject
                  Effect: Allow,
                  Resource:
                    - 'Fn::Join':
                      - ''
                      -
                        - 'arn:aws:s3:::'
                        - Ref: WebsiteMonitorErrorCountBucket
                        - '/*'
                -
                  Action:
                    - 'sns:Publish'
                  Effect: Allow
                  Resource:
                    - Ref: WebsiteMonitorAlertsTopic
                -
                  Action:
                    - 'logs:PutLogEvents'
                    - 'logs:DescribeLogStreams'
                    - 'logs:Create'
                  Effect: Allow
                  Resource:
                    - 'arn:aws:logs:*:*:*'

#  Outputs:
#     NewOutput:
#       Description: Description for the output
#       Value: Some output value
